<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.65.0" />
    <PackageReference Include="Grpc.Net.Client" Version="2.65.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MSSP\MSSP.csproj" />
    <ProjectReference Include="..\MSSP.Embedded\MSSP.Embedded.csproj" />
    <ProjectReference Include="..\MSSP.Grpc\MSSP.Grpc.csproj" />
    <ProjectReference Include="..\MSSP.Raft\MSSP.Raft.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\raft.proto" GrpcServices="Both" />
  </ItemGroup>

</Project>
