syntax = "proto3";

option csharp_namespace = "MSSP.Grpc";

package mssp;

enum ReadDirection {
  UNSPECIFIED = 0;
  FORWARDS = 1;
  BACKWARDS = 2;
}

service Mssp {
  rpc Append    (AppendRequest)    returns (AppendResponse);
  rpc Read      (ReadRequest)      returns (stream RecordedEvent);
  rpc Subscribe (SubscribeRequest) returns (stream SubscriptionEvent);
}

message AppendRequest {
  string             stream_id         = 1;
  sint64             expected_revision = 2;
  repeated EventData events            = 3;
}

message AppendResponse {}

message EventData {
  string event_type = 1;
  bytes  data       = 2;
}

message ReadRequest {
  string stream_id     = 1;
  uint64 from_revision = 2;
  ReadDirection direction = 3;
}

message RecordedEvent {
  string stream_id    = 1;
  uint64 revision     = 2;
  string event_type   = 3;
  bytes  data         = 4;
  int64  timestamp_ns = 5;
}

message SubscribeRequest {
  SubscriptionFilter filter        = 1;
  uint64             from_position = 2;
}

message SubscriptionEvent {
  string stream_id    = 1;
  uint64 revision     = 2;
  string event_type   = 3;
  bytes  data         = 4;
  int64  timestamp_ns = 5;
  uint64 position     = 6;
}

message SubscriptionFilter {
  oneof kind {
    AllFilter              all                = 1;
    StreamIdFilter         stream_id_filter   = 2;
    StreamPrefixFilter     stream_prefix      = 3;
    StreamPatternFilter    stream_pattern     = 4;
    EventTypeFilter        event_type_filter  = 5;
    EventTypePatternFilter event_type_pattern = 6;
    AndFilter              and                = 7;
  }
}

message AllFilter              {}
message StreamIdFilter         { string stream_id  = 1; }
message StreamPrefixFilter     { string prefix     = 1; }
message StreamPatternFilter    { string pattern    = 1; }
message EventTypeFilter        { string event_type = 1; }
message EventTypePatternFilter { string pattern    = 1; }
message AndFilter              { repeated SubscriptionFilter filters = 1; }
