<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_").Replace(".Tests", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="10.0.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MSSP\MSSP.csproj" />
    <ProjectReference Include="..\MSSP.BloomFilters\MSSP.BloomFilters.csproj" />
    <ProjectReference Include="..\MSSP.Client\MSSP.Client.csproj" />
    <ProjectReference Include="..\MSSP.Grpc\MSSP.Grpc.csproj" />
    <ProjectReference Include="..\MSSP.Embedded\MSSP.Embedded.csproj" />
    <ProjectReference Include="..\MSSP.Storage\MSSP.Storage.csproj" />
    <ProjectReference Include="..\MSSP.Server\MSSP.Server.csproj" />
    <ProjectReference Include="..\MSSP.Raft\MSSP.Raft.csproj" />
    <ProjectReference Include="..\MSSP.Cluster\MSSP.Cluster.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
