<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <VersionPrefix>0.1.0</VersionPrefix>
    <PackageId>$(AssemblyName)</PackageId>
    <Title>MSSP.Server</Title>
    <Authors>Wouter Naessens</Authors>
    <Product>MSSP</Product>
    <Description>ASP.NET Core gRPC server library for the MSSP event store.</Description>
    <PackageProjectUrl>https://github.com/FleaFX/mssp</PackageProjectUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.65.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MSSP\MSSP.csproj" />
    <ProjectReference Include="..\MSSP.Grpc\MSSP.Grpc.csproj" />
    <ProjectReference Include="..\MSSP.Raft\MSSP.Raft.csproj" />
  </ItemGroup>

</Project>
